### ISSUE TITLE
Cannot create BrowserWindow before app is ready

### ISSUE THREAD

**Issue by dalinaum** [dalinaum/IRCCloud#10]
```
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at Error (native)
    at openMainWindow (/Applications/IRCCloud.app/Contents/Resources/app/main.js:319:16)
    at EventEmitter.<anonymous> (/Applications/IRCCloud.app/Contents/Resources/app/main.js:344:3)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by Tux64** [comment]
Is this still an issue?
